networks:
  monitor:
    driver: bridge

services:
  spring-mvc-app:
    image: "swlee1999/deployment:latest"
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - monitor
    restart: always

  spring-webflux-app:
    image: "swlee1999/webflux"
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - monitor
    restart: always

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MY_PASSWORD}
      MYSQL_DATABASE: summary
    ports:
      - "3306:3306"
    networks:
      - monitor
    restart: always

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    networks:
      - monitor
    restart: always

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - monitor
    restart: always