spring:
  datasource:
    url: jdbc:mysql://localhost:3306/summary
    username: root
    password: ${MY_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  redis:
    data:
      host: ${REDIS_HOSTNAME}
      port: ${REDIS_PORT}
  jwt:
    secret: ${JWT_SECRET}
google:
  auth:
    url: https://oauth2.googleapis.com
  login:
    url: https://accounts.google.com/o/oauth2/v2/auth?
  redirect:
    url: ${REDIRECT_URL}
  client:
    id: ${GOOGLE_ID}
    pw: ${GOOGLE_PWD}